language: python
python:
    - 2.6
    - 2.7
    - 3.3
install:
    - pip install --upgrade setuptools>=1.4
    - pip install zc.buildout
    - buildout
script:
    - ./bin/test
notifications:
    email: false
