language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
install:
    - pip install --upgrade setuptools>=1.4
    - pip install --upgrade zc.buildout>=2.2.1
    - buildout bootstrap
    - ./bin/buildout
script:
    - ./bin/test
notifications:
    email: false
